config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.urls import include, path
from django.views import defaults as default_views

from project.core.views import HomeView, RegioneDetailView, SettoreDetailView, EntePartecipatoDetailView, \
    EnteControllanteDetailView, EntePartecipatoSearchView, EnteControllanteSearchView

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),

    path('', login_required(HomeView.as_view()), name='home'),
    path('regioni/<slug:slug>/', login_required(RegioneDetailView.as_view()), name='regione_detail'),
    path('settori/<slug:slug>/', login_required(SettoreDetailView.as_view()), name='settore_detail'),
    path('partecipate/', login_required(EntePartecipatoSearchView.as_view()), name='entepartecipato_search'),
    path('partecipate/<int:pk>/', login_required(EntePartecipatoDetailView.as_view()), name='entepartecipato_detail'),
    path('partecipanti/', login_required(EnteControllanteSearchView.as_view()), name='entecontrollante_search'),
    path('partecipanti/<int:pk>/', login_required(EnteControllanteDetailView.as_view()), name='entecontrollante_detail'),

    path('accounts/login/', LoginView.as_view(), name='login'),

    path('api/', include('project.core.api.urls')),

    # ckeditor uploader
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

    if settings.DEBUG_TOOLBAR:
        import debug_toolbar
        urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

project/core/api/urls.py
from django.urls import include, path, re_path
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from .views import *

router = routers.SimpleRouter()
router.register(r'partecipate', EntePartecipatoViewSet, basename='api-entepartecipato')
router.register(r'regioni', RegioneViewSet, basename='api-regione')
router.register(r'settori', SettoreViewSet, basename='api-settore')

urlpatterns = [
    re_path(r'^$', ApiRootView.as_view(), name='api-root'),

    path('dati-aggregati/', AggregatoHomeView.as_view(), name='api-aggregati-home'),
    path('dati-aggregati/regioni/<slug:slug>/', AggregatoRegioneDetailView.as_view(), name='api-aggregati-regione-detail'),
    path('dati-aggregati/settori/<slug:slug>/', AggregatoSettoreDetailView.as_view(), name='api-aggregati-settore-detail'),

    path('', include(router.urls)),

    # path('auth/', include('rest_framework.urls', namespace='rest_framework'))
]

urlpatterns = format_suffix_patterns(urlpatterns)

project/core/models.py
import urllib.parse
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django_extensions.db.fields import AutoSlugField


# class Provincia(models.Model):
#     sigla = models.CharField(max_length=2, primary_key=True)
#     denominazione = models.CharField(max_length=30, unique=True)
#
#     def __str__(self):
#         return self.denominazione
#
#     class Meta:
#         ordering = ('denominazione',)


class Categoria(models.Model):
    GRUPPO_CHOICES = (
        ('categoria', 'Categoria'),
        ('governance', 'Governance'),
        ('sottotipo', 'Sottotipo'),
        ('tipologia', 'Tipologia'),
        ('tipologia_entecontrollante', 'Tipologia Ente Controllante'),
    )

    gruppo = models.CharField(max_length=30, choices=GRUPPO_CHOICES)
    denominazione = models.CharField(max_length=256)
    slug = AutoSlugField(populate_from='denominazione', max_length=100, unique=True)

    def __str__(self):
        return self.denominazione

    class Meta:
        ordering = ('gruppo', 'denominazione')
        unique_together = ('gruppo', 'denominazione')
        verbose_name_plural = 'categorie'


class EntePartecipato(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    denominazione = models.CharField(max_length=255)
    codice_fiscale = models.CharField(max_length=16, null=True, blank=True)
    # regione = models.ForeignKey(Regione, related_name='enti_partecipati', on_delete=models.CASCADE)
    # provincia = models.ForeignKey(Provincia, related_name='enti_partecipati', on_delete=models.CASCADE, null=True, blank=True)
    provincia = models.CharField(max_length=100, null=True, blank=True)
    comune = models.CharField(max_length=100, null=True, blank=True)
    indirizzo = models.CharField(max_length=100, null=True, blank=True)
    anno_inizio_attivita = models.CharField(max_length=4)
    # anno_fine_attivita = models.CharField(max_length=4, null=True, blank=True)
    sottotipo = models.ForeignKey(Categoria, limit_choices_to={'gruppo': 'sottotipo'}, related_name='ente_partecipato_by_sottotipo', on_delete=models.CASCADE)
    tipologia = models.ForeignKey(Categoria, limit_choices_to={'gruppo': 'tipologia'}, related_name='ente_partecipato_by_tipologia', on_delete=models.CASCADE)
    governance = models.ForeignKey(Categoria, limit_choices_to={'gruppo': 'governance'}, related_name='ente_partecipato_by_governance', on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, limit_choices_to={'gruppo': 'categoria'}, related_name='ente_partecipato_by_categoria', on_delete=models.CASCADE)

    @cached_property
    def cronologie_attive(self):
        return [o for o in self.cronologia.all() if o.stato != 'C']

    @cached_property
    def ultima_cronologia(self):
        try:
            return self.cronologie_attive[-1]
        except IndexError:
            return None

    @property
    def in_attivita(self):
        for obj in self.cronologia.all():
            if obj.stato == 'C':
                return False
        return True

    @property
    def anno_fine_attivita(self):
        for obj in self.cronologia.all():
            if obj.stato == 'C':
                return obj.anno_rilevazione
        return None

    def get_absolute_url(self):
        return reverse('entepartecipato_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.denominazione

    class Meta:
        verbose_name_plural = 'enti partecipati'


class EntePartecipatoCronologiaQuerySet(models.QuerySet):
    def attive(self):
        return self.exclude(stato='C')

    def ultimo_anno_rilevazione(self):
        return self.values_list('anno_rilevazione', flat=True).order_by('anno_rilevazione').distinct().last()


class EntePartecipatoCronologia(models.Model):
    STATO_CHOICES = (
        ('C', 'Cessato'),
        ('N', 'Nuovo'),
        ('P', 'Presente'),
    )
    LIVELLO_PARTECIPAZIONE_CHOICES = (
        ('1', 'primo'),
        ('2', 'secondo'),
    )

    ente_partecipato = models.ForeignKey(EntePartecipato, related_name='cronologia', on_delete=models.CASCADE)
    anno_rilevazione = models.CharField(max_length=4, db_index=True)
    stato = models.CharField(max_length=1, choices=STATO_CHOICES)
    quotato = models.NullBooleanField()
    dipendenti = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    entrate_totali = models.BigIntegerField(null=True, blank=True)
    spese_totali = models.BigIntegerField(null=True, blank=True)
    spese_investimenti = models.BigIntegerField(null=True, blank=True)
    spese_personale = models.BigIntegerField(null=True, blank=True)
    numero_unita_locali = models.SmallIntegerField(null=True, blank=True)
    livello_partecipazione = models.CharField(max_length=1, choices=LIVELLO_PARTECIPAZIONE_CHOICES, null=True, blank=True)

    objects = EntePartecipatoCronologiaQuerySet.as_manager()

    @property
    def partecipazione_pubblica(self):
        return sum(o.quota for o in self.entecontrollantequota_set.all())

    @property
    def spese_investimenti_perc(self):
        return self._spese_perc(self.spese_investimenti)

    @property
    def spese_personale_perc(self):
        return self._spese_perc(self.spese_personale)

    def _spese_perc(self, spese):
        return round(100 * (spese or 0) / self.spese_totali, 1) if self.spese_totali else None

    class Meta:
        ordering = ('ente_partecipato', 'anno_rilevazione')
        unique_together = ('ente_partecipato', 'anno_rilevazione')
        index_together = [
            ('ente_partecipato', 'anno_rilevazione'),
        ]
        verbose_name_plural = 'cronologie enti partecipati'


class EnteControllante(models.Model):
    denominazione = models.CharField(max_length=255, null=True, blank=True)
    codice_fiscale = models.CharField(max_length=16, null=True, blank=True)
    tipologia = models.ForeignKey(Categoria, limit_choices_to={'gruppo': 'tipologia_entecontrollante'}, related_name='+', on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('entecontrollante_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.denominazione or self.tipologia.denominazione

    class Meta:
        verbose_name_plural = 'enti controllanti'


class EnteControllato(models.Model):
    denominazione = models.CharField(max_length=255)
    codice_fiscale = models.CharField(max_length=16, null=True, blank=True)

    def __str__(self):
        return self.denominazione

    class Meta:
        verbose_name_plural = 'enti controllati'


class Regione(models.Model):
    denominazione = models.CharField(max_length=30, unique=True)
    slug = AutoSlugField(populate_from='denominazione', max_length=30, unique=True)
    codice = models.CharField(max_length=5, unique=True)

    def get_search_filter_querystring(self):
        return urllib.parse.urlencode({'selected_facets': 'regione:{}'.format(self.slug)}, safe=':')

    def get_absolute_url(self):
        return reverse('regione_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.denominazione

    class Meta:
        ordering = ('denominazione',)
        verbose_name_plural = 'regioni'


class Settore(models.Model):
    denominazione = models.CharField(max_length=50)
    slug = AutoSlugField(populate_from='denominazione', max_length=50, unique=True)
    codice = models.CharField(max_length=5, unique=True)

    def get_search_filter_querystring(self):
        return urllib.parse.urlencode({'selected_facets': 'settore:{}'.format(self.slug)}, safe=':')

    def get_absolute_url(self):
        return reverse('settore_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.denominazione

    class Meta:
        ordering = ('denominazione',)
        verbose_name_plural = 'settori'


class BaseQuota(models.Model):
    ente_partecipato_cronologia = models.ForeignKey(EntePartecipatoCronologia, on_delete=models.CASCADE)
    quota = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        ordering = ['ente_partecipato_cronologia', '-quota']
        abstract = True


class BaseQuotaEnte(BaseQuota):
    progressivo = models.SmallIntegerField()

    class Meta(BaseQuota.Meta):
        abstract = True


class EnteControllanteQuota(BaseQuotaEnte):
    ente_controllante = models.ForeignKey(EnteControllante, related_name='quote', on_delete=models.CASCADE)

    class Meta(BaseQuotaEnte.Meta):
        # ordering = ['ente_partecipato_cronologia', 'ente_controllante']
        unique_together = ('ente_partecipato_cronologia', 'ente_controllante')
        index_together = [
            ['ente_partecipato_cronologia', 'ente_controllante'],
        ]
        verbose_name_plural = 'quote enti controllanti'


class EnteControllatoQuota(BaseQuotaEnte):
    ente_controllato = models.ForeignKey(EnteControllato, related_name='quote', on_delete=models.CASCADE)

    class Meta(BaseQuotaEnte.Meta):
        # ordering = ['ente_partecipato_cronologia', 'ente_controllato']
        unique_together = ('ente_partecipato_cronologia', 'ente_controllato')
        index_together = [
            ['ente_partecipato_cronologia', 'ente_controllato'],
        ]
        verbose_name_plural = 'quote enti controllati'


class RegioneQuota(BaseQuota):
    regione = models.ForeignKey(Regione, related_name='quote', on_delete=models.CASCADE)

    class Meta(BaseQuota.Meta):
        # ordering = ['ente_partecipato_cronologia', 'regione']
        unique_together = ('ente_partecipato_cronologia', 'regione')
        index_together = [
            ['ente_partecipato_cronologia', 'regione'],
        ]
        verbose_name_plural = 'quote regioni'


class SettoreQuota(BaseQuota):
    settore = models.ForeignKey(Settore, related_name='quote', on_delete=models.CASCADE)

    class Meta(BaseQuota.Meta):
        # ordering = ['ente_partecipato_cronologia', 'settore']

project/enhancedsearch/forms.py
# -*- coding: utf-8 -*-
from haystack.forms import SearchForm


format_facet_field = lambda x: '{{!ex={0}_tag}}{0}'.format(x)


class MultiSelectWithRangeFacetedSearchForm(SearchForm):
    def __init__(self, *args, **kwargs):
        self.selected_facets = kwargs.pop('selected_facets', [])
        super().__init__(*args, **kwargs)

    def no_query_found(self):
        return self.searchqueryset.all()

    def search(self):
        sqs = super().search()

        for field, values in self._parse_selected_facets(self.selected_facets).items():
            if values:
                field = '{{!tag={0}_tag}}{0}'.format(field)
                sqs = sqs.narrow('{}:({})'.format(field, ' OR '.join(v if v.startswith(('[', '{')) and v.endswith((']', '}')) else '"{}"'.format(sqs.query.clean(v)) for v in values)))

        return sqs

    def _parse_selected_facets(self, facets):
        from collections import defaultdict

        parsed_facets = defaultdict(list)

        for facet in facets:
            if ':' in facet:
                field, value = facet.split(':', 1)
                parsed_facets[field].append(value)

        return parsed_facets

project/enhancedsearch/views.py
# -*- coding: utf-8 -*-
from haystack.generic_views import FacetedSearchView
from .forms import MultiSelectWithRangeFacetedSearchForm, format_facet_field


class MultiSelectWithRangeFacetedSearchView(FacetedSearchView):
    load_all = False
    form_class = MultiSelectWithRangeFacetedSearchForm
    model = None
    facet_fields = ()
    FACETS = ()
    RANGES = {}

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.model:
            queryset = queryset.models(self.model)

        for name in self.FACETS:
            queryset = queryset.facet(format_facet_field(name))

        for name in self.RANGES:
            for range in self.RANGES[name]:
                queryset = queryset.query_facet(format_facet_field(name), self.RANGES[name][range]['qrange'])

        return queryset

    @staticmethod
    def _get_objects_by_pk(pks):
        return {}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        objects_by_pk = self._get_objects_by_pk(object.pk for object in context['object_list'])
        for object in context['object_list']:
            try:
                object.object = objects_by_pk[object.pk]
            except KeyError:
                pass

        return context

    def _build_facet_field_info(self, field, label, key_to_labels):
        facet_counts_fields = self.queryset.facet_counts().get('fields', {})

        facet = {}
        if field in facet_counts_fields:
            facet['label'] = label
            facet['values'] = [
                {
                    'key': c[0],
                    'label': key_to_labels.get(c[0], c[0]),
                    'count': c[1],
                    'urls': self._get_facet_urls(field, c[0]),
                } for c in facet_counts_fields[field]]

        return facet

    def _build_range_facet_queries_info(self, field, label):
        facet_counts_queries = self.queryset.facet_counts().get('queries', {})

        facet = {}
        if field in self.RANGES:
            ranges = self.RANGES[field]

            facet['label'] = label
            facet['values'] = [
                {
                    'key': ranges[range]['qrange'],
                    'label': ranges[range]['label'],
                    'count': facet_counts_queries.get('{}:{}'.format(format_facet_field(field), ranges[range]['qrange'])),
                    'urls': self._get_facet_urls(field, ranges[range]['qrange']),
                } for range in sorted(ranges.keys())]

        return facet

    def _get_facet_urls(self, facet, key):
        facet_key = '{}:{}'.format(facet, key)

        params = self.params

        urls = {'add_filter': False, 'remove_filter': False}

        selected_facets = params.getlist('selected_facets')
        if facet_key in selected_facets:
            selected_facets.remove(facet_key)
            k = 'remove_filter'
        else:
            selected_facets.append(facet_key)
            k = 'add_filter'
        params.setlist('selected_facets', selected_facets)
        urls[k] = params.urlencode(safe=':')

        return urls

    @property
    def params(self):
        params = self.request.GET.copy()

        if 'q' not in params:
            params['q'] = ''
        if 'page' in params:
            del(params['page'])

        params.setlist('selected_facets', sorted(set(params.getlist('selected_facets'))))

        return params

project/templates/search/search.html
{% extends 'base.html' %}

{% load digg_paginator capture utils %}

{% block page_title %}Ricerca {% if model_name == 'entepartecipato' %}partecipate{% elif model_name == 'entecontrollante' %}partecipanti{% endif %}{% endblock %}

{% block content %}
    <main>
        <section id="dashboard" class="container-lg px-lg-4">
            <h1 class="text-center font-weight-bold my-5">{{ paginator.count }} {% if model_name == 'entepartecipato' %}partecipat{{ paginator.count|pluralize:'a,e' }}{% elif model_name == 'entecontrollante' %}partecipant{{ paginator.count|pluralize:'e,i' }}{% endif %} trovat{{ paginator.count|pluralize:'a,e' }}</h1>
            <div class="row mx-lg-n4">
                <div class="col-lg-4 px-lg-4">
                    {% capture activefilters %}{% spaceless %}
                        {% for facet in my_facets %}
                            {% for v in facet.values %}
                                {% if v.urls.remove_filter %}
                                    <li>
                                        <a href="?{{ v.urls.remove_filter }}" title="Rimuovi questo filtro" class="btn">x</a>
                                        <span>{{ facet.label }}:<br/>{{ v.label }}</span>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        {% endfor %}
                    {% endspaceless %}{% endcapture %}

                    {% if activefilters %}
                        <div id="selected-filters" class="bg-celeste mb-5">
                            <div class="d-flex justify-content-between align-items-center mb-3">
                                <h5><strong>Selezione</strong></h5>
                                <a href="?q=" class="fs-13">CANCELLA TUTTI</a>
                            </div>
                            <ul>
                                {{ activefilters }}
                            </ul>
                        </div>
                    {% endif %}

                    <h2 class="p-3">Affina la ricerca</h2>

                    <div id="search-filters" class="accordion">
                        {% for facet in my_facets %}
                            {% if facet.values %}
                                <div class="card">
                                    <div class="card-header" id="head-{{ forloop.counter }}">
                                        <h5 class="mb-0">
                                            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#card-{{ forloop.counter }}" aria-expanded="true" aria-controls="card-{{ forloop.counter }}">
                                                <span class="collapse-open"></span>
                                                <span class="collapse-close"></span>
                                                {{ facet.label }}
                                            </button>
                                        </h5>
                                    </div>
                                    <div id="card-{{ forloop.counter }}" class="collapse" aria-labelledby="head-{{ forloop.counter }}">
                                        <div class="card-body">
                                            <ul>
                                                {% for v in facet.values %}
                                                    <li>
                                                        {% if v.urls.add_filter %}
                                                            <a href="?{{ v.urls.add_filter }}">{{ v.label }} <span class="celeste">({{ v.count|default_if_none:0 }})</span></a>
                                                        {% else %}
                                                            {{ v.label }} ({{ v.count|default_if_none:0 }})
                                                        {% endif %}
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>

                <div class="col-lg-8 px-lg-4">
                    {% if orderby_choices %}
                        <div id="search-order" class="bb-1">
                            <form action="#" method="get" autocomplete="off">
                                <label for="order-by">Ordina per</label>
                                <select id="order-by">
                                    {% for choice in orderby_choices %}
                                        <option value="?{{ choice.query_string|iriencode }}"{% if choice.selected %} selected{% endif %}>{{ choice.display }}</option>
                                    {% endfor %}
                                </select>
                            </form>
                        </div>
                    {% endif %}

                    <div id="search-results">
                        <ul>
                            {% for result in object_list %}
                                {% with object=result.object %}
                                    <li class="{{ result.model_name }}{% if result.model_name == 'entepartecipato' %} {{ object.in_attivita|yesno:'attivo,cessato' }}{% endif %}">
                                        <h5><a href="{{ object.get_absolute_url }}">{{ object.denominazione }}</a></h5>
                                        {% if result.model_name == 'entepartecipato' %}
                                            <span class="celeste">Dimensione delle entrate:</span> € {{ object.ultima_cronologia.entrate_totali|bignumberformat }} |
                                            <span class="celeste">Dimensione della spesa:</span> € {{ object.ultima_cronologia.spese_totali|bignumberformat }}<br/>
                                            <span class="celeste">Spesa per il personale:</span> {{ object.ultima_cronologia.spese_personale_perc|percentageformat }} |
                                            <span class="celeste">Spesa per gli investimenti:</span> {{ object.ultima_cronologia.spese_investimenti_perc|percentageformat }}<br/>
                                            Categoria: <strong>{{ object.categoria }}</strong><br/>
                                            Sottotipo: <strong>{{ object.sottotipo }}</strong><br/>
                                            Settori d'attività: <strong>{% for item in object.ultima_cronologia.settorequota_set.all %}{{ item.settore }} {{ item.quota|percentageformat }}{% if not forloop.last %}, {% endif %}{% endfor %}</strong><br/>
                                            Regioni d'attività: <strong>{% for item in object.ultima_cronologia.regionequota_set.all %}{{ item.regione }} {{ item.quota|percentageformat }}{% if not forloop.last %}, {% endif %}{% endfor %}</strong>
                                        {% elif result.model_name == 'entecontrollante' %}
                                            <span class="celeste">Partecipate:</span> {{ object.numero_partecipate }}<br/>
                                            Tipologia: <strong>{{ object.tipologia }}</strong><br>
                                        {% endif %}
                                    </li>
                                {% endwith %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>

            <div class="my-5">
                {% digg_paginator %}
            </div>
        </section>
    </main>
{% endblock %}